### ISSUE TITLE
URL http://127.0.0.1:7026/static/(.+) not supported

### ISSUE THREAD

**Issue by u2003** [mshibanami/redirect-web#10]
I use a service called SimpRead to read my local html files, which makes it possible to open local html files via urls like http://127.0.0.1:7026/static/23%2FBackups%20-%20Anki%20Manual.html. As I set Safari as my default browser, for which SimpRead has no extension to annotate the html files, I would like to redirect urls like this to Microsoft Edge. Could you please support this kind of url? It would be highly highly appreciated if so.

**Comment by u2003** [comment]
I tried redirecting a url like this, but was prompted that the url is invalid.

**Comment by mshibanami** [comment]
Hi @u2003, sorry for the late reply.

I'm wondering if the prompt you saw was this.:

> The format of the redirect destination URL is invalid.

If so, perhaps you didn't input anything in the Redirect To section. You will need to set `$0` to it like this:

![Screenshot 2023-08-14 at 6 45 39 pm](https://github.com/mshibanami/redirect-web/assets/1333214/6e55bfe2-1a29-411c-b619-f4aeb7adcce6)

You can see more details here: https://mshibanami.github.io/redirect-web/#/redirect-rule?id=url-pattern

**Comment by mshibanami** [comment]
I'm closing this issue for now because of no responses. Please feel free to reopen it if your issue persists.
