### ISSUE TITLE
Change the site-generating tool from Docsify

### ISSUE THREAD

**Issue by mshibanami** [mshibanami/redirect-web#49]
This issue is to track the progress of migrating from Docsify to an alternative.

## Motivation

Redirect Web's support website is generated using Docsify, which is undoubtedly a great tool. However, normal search engines only index the top page (mshibanami.github.io/redirect-web) because the site is dynamically generated.

When I first created the support website, I wasn't overly concerned about this issue since the documentation didn't have much content. However, now that I've added many tips, warnings, and other information, it's time to reconsider my choice. Reaching this information through search engines is crucial, and I can't ignore that.

According to https://github.com/docsifyjs/docsify/issues/136#issuecomment-1973556725, the Docsify team has decided not to support SSG for now. Therefore, I should look for an alternative.

## Candidates

Before adopting Docsify, I considered Docusaurus, GitBook, and a few others, but I didn't choose them. I can't remember why, but it's been two years since then, so it's time to take another look.

**Comment by Fmstrat** [comment]
In the same boat, so following.
