### ISSUE TITLE
Unable to disable rules

### ISSUE THREAD

**Issue by adamcstephens** [mshibanami/redirect-web#7]
When I toggle a rule to disabled, the rule does not actually disable. If I close the Safari pane and reopen it, the rule will show it is still enabled. Same thing for the app itself.

**Comment by mshibanami** [comment]
Hi @adamcstephens, thanks for reporting it.
Sorry it’s a bug. I thought I fixed it but I’ll have another look soon.

As a temporary workaround, you may be able to resolve this issue by reordering your redirect rules in the app or by adding/deleting a rule. Could you please try this and see if it helps for now?

**Comment by adamcstephens** [comment]
Hi, yes that did provide a workaround. Thanks.

**Comment by mshibanami** [comment]
Hi @adamcstephens, I released a new version `5.0.0`, which completely solves this issue.

For your information, this was happening when the rule came from another device synchronised through iCloud. In other words, the extension failed to manage the enabled/disabled status for those rules. Now it should manage correctly.

Thank you so much for your report. Now I'm going to close this issue.

**Comment by adamcstephens** [comment]
Thank you!
